CREATE TABLE reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reservations_code BIGINT NOT NULL,
   check_in_date date NOT NULL,
   check_out_date date NOT NULL,
   reservation_value DECIMAL NOT NULL,
   reservation_status SMALLINT,
   customer_id INT,
   CONSTRAINT pk_reservations PRIMARY KEY (id)
);

ALTER TABLE reservations ADD CONSTRAINT uc_reservations_reservations_code UNIQUE (reservations_code);

ALTER TABLE reservations ADD CONSTRAINT FK_RESERVATIONS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);